# H2 Datenbank (Speicherort: Arbeitsspeicher)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Tabellen jedes Mal neu erstellen
spring.jpa.hibernate.ddl-auto=create-drop

# Testdaten automatisch laden
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 Console aktivieren (unter localhost:8080/h2-console)
spring.h2.console.enabled=true