spring.application.name=bibliothek

spring.datasource.url=jdbc:mariadb://localhost:3306/bibliothek
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true